spring:
  application:
    name: quantscope
  # DataSource Configuration
  datasource:
    driver-class-name:
#    url: jdbc:mysql://localhost:3306/quantscope
#    username: root
#    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  # Session expiration time (minutes)
#  session:
#    timeout: 86400
#    store-type: redis
#  # Redis configuration
#  data:
#    redis:
#      port: 6379
#      host: localhost
#      database: 0
server:
  port: 8123
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # Global logical deletion entity field name (since 3.3.0, can be ignored after configuration without configuring step 2)
      logic-delete-value: 1 # Logical deleted value (default to 1)
      logic-not-delete-value: 0 # Logical not deleted value (default to 0)
# This configuration is for testing only, in actual scenarios, ak and sk should be obtained based on the logged-in user

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
#    address: nacos://192.168.174.128:8848
jwt:
  secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32BYTES"
  expire-seconds: 900   # 15 minutes