spring:
  application:
    name: quantscope-rag-service
  rabbitmq:
    host: 192.168.174.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/quantscope?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

rag:
  mq:
    exchange: rag.job.exchange
    routing-key: rag.job.requested
